In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.6.0+cu124


introduction to tensors

In [3]:
# creating tensors

# scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [7]:
# vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [10]:
# matrix

matrix = torch.tensor([[23,34],[45,56]])
matrix

tensor([[23, 34],
        [45, 56]])

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix.ndim

2

In [14]:
matrix[0]

tensor([23, 34])

In [15]:
matrix[1]

tensor([45, 56])

In [16]:
# tensor

tensor = torch.tensor([[1,2,3],[3,4,5],[5,6,7]])
tensor

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [17]:
tensor.ndim

2

In [18]:
tensor.shape

torch.Size([3, 3])

Random Tensors

In [19]:
random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.1414, 0.8203, 0.1857, 0.7582],
        [0.3899, 0.3519, 0.7378, 0.0549],
        [0.4586, 0.0190, 0.0895, 0.9618]])

In [20]:
random_tensors = torch.rand(3,3)
random_tensors

tensor([[0.6398, 0.9432, 0.4767],
        [0.9427, 0.0426, 0.0417],
        [0.3121, 0.5181, 0.3259]])

In [21]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
torch.range(0,10)

<ipython-input-24-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
one_to_ten = torch.zeros_like(input=one_to_ten)
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
#Manipulating Tensors

#Addition
#Subtraction
#Multiplication(element wise)
#Division
#Matrix Multiplication


In [29]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor*10

tensor([10, 20, 30])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
torch.add(tensor,5)

tensor([6, 7, 8])

In [35]:
# Matrix multiplication
#Inner dimesnsions must match:
#(3,2) @ (3,2)-- Wont Work
#(3,2) @ (2,3)-- Will work
#(2,3) @ (3,2)-- Will work


In [38]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [36]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.3144, 0.3200],
        [0.5688, 0.4918]])

In [39]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3473, 0.9779, 0.5640],
        [0.1481, 0.5173, 0.2991],
        [0.0719, 0.2519, 0.1457]])

In [40]:
# Tensor Aggregation(max,min,sum,mean etc)

In [42]:
# create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
# find the min
torch.min(x)

tensor(0)

In [46]:
x.min()

tensor(0)

In [45]:
# find the max
torch.max(x)

tensor(90)

In [47]:
x.max()

tensor(90)

In [48]:
# find the mean

torch.mean(x.type(torch.float32))

tensor(45.)

In [49]:
x.type(torch.float32).mean()

tensor(45.)

In [50]:
# find the sum

torch.sum(x)

tensor(450)

In [51]:
x.sum()

tensor(450)

In [53]:
# find the positional min and max

x.argmin()

tensor(0)

In [54]:
x.argmax()

tensor(9)

In [55]:
x[9]

tensor(90)

In [57]:
# reshaping

# let's creat a tensor

import torch
x = torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [58]:
# add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# view

z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# changing z changes x

z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [62]:
x_stacked =torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
# torch.squeeze() - removes all singal dimensions from target tensor

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
x_reshaped.shape

torch.Size([1, 9])

In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
x_reshaped.squeeze().shape

torch.Size([9])