In [106]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [107]:
tf.__version__

'2.18.0'

In [108]:
tf.test.is_gpu_available()

False

In [109]:
x=tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [110]:
y=tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [111]:
z=tf.constant("india")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'india'>

In [112]:
s=tf.constant([1,2,3,4,5])
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [113]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [114]:
t_2d=tf.constant([[10,11,12],[13,14,15]])
t_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15]], dtype=int32)>

In [115]:
t_1d=tf.constant([10,11,12])
t_1d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 11, 12], dtype=int32)>

In [116]:
t_2d_1=tf.constant([1,2,3,4],shape=(2,2))
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [117]:
t_2d_2=tf.constant([[1,2,3],[4,5,6]],shape=(2,3),dtype="float32")
t_2d_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [118]:
t_3d_1=tf.constant([[1,2],[3,4],[5,6]],dtype="float32")
t_3d_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [119]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [120]:
t_3d_1.shape

TensorShape([3, 2])

Tensor Variable

In [121]:
# Variable constructor requires an initial value for the variable
# which can be a tensor of any type & shape.
# This initial value defines the type & shape of the variable.
# After construction the type & shape of the variable are fixed.

In [122]:
import tensorflow as tf

In [123]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [124]:
x=tf.Variable([[1,2],[3,4],[5,6]])
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [125]:
x.name

'Variable:0'

In [126]:
x.shape

TensorShape([3, 2])

In [127]:
x.dtype

tf.int32

In [128]:
y=tf.Variable([1.0,3.3,5])
y

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1. , 3.3, 5. ], dtype=float32)>

In [129]:
z=tf.Variable(True,False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [130]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [131]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

Create Tensorflow variable with different Shape

In [132]:
t_2d=tf.Variable([[1,2],[3,4],[5,6]])
t_2d

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [133]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [134]:
tf.reshape(x,[2,3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

GET INDEX OF HIGHEST VALUE

In [135]:
t_2d

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [136]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2])>

In [137]:
# viewed/convert as a tensor

In [138]:
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [139]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [140]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [141]:
# Change/Assign New Value To Tensor

In [142]:
x=tf.Variable([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [143]:
x.assign([5,6,7,8,9])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>

In [144]:
# Assign Variable With Another Memory

In [145]:
x.assign_add([3,4,5,6,7])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 8, 10, 12, 14, 16], dtype=int32)>

TENSORFLOW MATH MODULE

In [146]:
import tensorflow as tf
import numpy as np

In [147]:
a=23
b=45

In [148]:
a+b

68

In [149]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [150]:
# addition of two list
l1=[3,4,5,6]
l2=[9,8,7,6]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 12, 12, 12], dtype=int32)>

In [151]:
# addition of two tuples
t1=(1,2,3,4)
t2=(5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [152]:
l1=[44,55,66,77]
a=10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([54, 65, 76, 87], dtype=int32)>

In [153]:
# Given a tensor x and a tensor y, this operation x^y computes for corresponding elements in x and y
x=tf.constant([[2,3],[4,5]])
y=tf.constant([[3,4],[5,6]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[    8,    81],
       [ 1024, 15625]], dtype=int32)>

In [154]:
# tf.math.abs

# real number
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [155]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [156]:
# tf.math.subtract
x=[3,4,5,6]
y=1
tf.subtract(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [157]:
x=[1,2,3,4,5]
y=1
tf.subtract(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [158]:
x=[1,2,3,4,5]
y=1
tf.subtract(y,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [159]:
# tf.math.multiply
import tensorflow as tf
x=tf.constant([1,2,3,4])
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [160]:
tf.math.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [161]:
tf.multiply(11,22)

<tf.Tensor: shape=(), dtype=int32, numpy=242>

In [162]:
x=tf.ones([1,2])
y=tf.ones([2,3])
tf.matmul(x,y)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[2., 2., 2.]], dtype=float32)>

In [163]:
x=tf.ones([1,2]);
y=tf.ones([2,3]);
x * y

InvalidArgumentError: {{function_node __wrapped__Mul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [1,2] vs. [2,3] [Op:Mul] name: 

In [164]:
x = tf.ones([1, 2]);
y = tf.ones([2, 1]);
x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [165]:
# tf.math.maximum
x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,-5.,4.,0.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 4., 0.], dtype=float32)>

In [166]:
x=tf.constant([0.,2.,0.,0.])
y=tf.constant([-2.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 2., 0., 0.], dtype=float32)>

In [167]:
# tf.math.minimum
x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,-5.,4.,0.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-2., -5.,  0.,  0.], dtype=float32)>

In [168]:
x=tf.constant([0.,2.,0.,-10.])
y=tf.constant([-2.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ -2.,  -2.,  -2., -10.], dtype=float32)>

In [169]:
# tf.math.log
x=tf.constant([1,2.4,5.,-4])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 0.8754688, 1.609438 ,       nan], dtype=float32)>

In [170]:
# tf.math.divide
x=tf.constant([1,2,3,4])
y=tf.constant([5,6,7,8])
tf.math.divide(x,y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [171]:
# tf.math.divide
x=tf.constant([1,2,3,4])
y=tf.constant([5,6,7,8])
tf.divide(x,y)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [172]:
# tf.math.pow
x=tf.constant([1,2,3,4])
y=tf.constant([5,6,7,8])
tf.math.pow(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([    1,    64,  2187, 65536], dtype=int32)>

In [173]:
# tf.math.sqrt
x=tf.constant([[1.,2.,3.,4.],[4.,5.,6.,7.]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508, 2.       ],
       [2.       , 2.236068 , 2.4494898, 2.6457512]], dtype=float32)>

In [174]:
x=tf.constant([[2.,-3.],[3.,4.]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135,       nan],
       [1.7320508, 2.       ]], dtype=float32)>

In [175]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [176]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [177]:
ones_2d=tf.ones((3,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [178]:
ones_3d=tf.ones((3,3,3)),tf.float32
ones_3d

(<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 tf.float32)

In [179]:
ones_3d=tf.ones((3,3,3),tf.float32)
ones_3d

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [180]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [181]:
zeros_2d=tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [182]:
# Ones_like:Creates a tensor of all ones that has the same shape as the input.
tensor=tf.constant([[1,2,3],[4,5,6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [183]:
tensor=tf.constant([[1,2,3],[4,5,6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## **Placeholder**-Migrate tensorflow 1 code to tensorflow 2

---


Place holder is a variable that we will assign data to at a later date.

In [184]:
import tensorflow as tf

In [185]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [206]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [189]:
tf.compat.v1.disable_eager_execution()

In [190]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [191]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [192]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [193]:
import numpy as np

In [194]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [195]:
with tf.compat.v1.Session() as sess:
   d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [196]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

Sparse Tensors


It enables efficient storage & processing of tensors that contains lot of zero values

In [199]:
tf.SparseTensor

tensorflow.python.framework.sparse_tensor.SparseTensor

In [200]:
tf.SparseTensor(indices=[[1,2],[2,3]],values=[1,2],dense_shape=[3,4])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [201]:
st1=tf.SparseTensor(indices=[[0,3],[3,4]],values=[10,20],dense_shape=[4,5])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [202]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


In [203]:
import tensorflow as tf

In [204]:
x=tf.compat.v1.get_variable("x",dtype=tf.int32,initializer=tf.constant([10]))
y=tf.compat.v1.get_variable("y",dtype=tf.int32,initializer=tf.constant([100]))
z=x+y

In [205]:
c=tf.constant([10],name="constant")
square=tf.constant([5],name="square")
f=tf.multiply(x,y)+tf.pow(x,square) +y +c
f

<tf.Tensor 'add_4:0' shape=(1,) dtype=int32>